### ISSUE TITLE
Dark Souls Code

### ISSUE THREAD

**Issue by Krenk0** [LordApple/SXOS-CheatDB#16]
Hi! I was trying the Dark Souls codes and everything was Ok (even the SXOS showed the "activated" green word) but nothing happened in the game. I don't know if it's my problem about don't know how to use the cheats or they're not working. Did someone else had any issue?

**Comment by MentalBlank** [comment]
Make sure your Version is 1.0.2 and that the title and build ID's are correct and attempt putting your switch into sleep mode and waking it back up after activating the cheats.

I also mentioned this in issue #17

**Comment by dnetbandit** [comment]
Good morning, 

I am having the same issues..  I think i am using the file correctly though i have another issue along with the codes not working.  My game keeps crashing when i activate the codes.  On some occasions depending on the cheat activated like the souls cheat, nothing happens.  Can this please be addressed?  I did verify i am on version 1.0.2 of the game.

Doug

**Comment by dnetbandit** [comment]
I apologize. Thank you for clearing that up.

Doug
