### ISSUE TITLE
0100646009fbe000 does not function

### ISSUE THREAD

**Issue by rayang2004** [LordApple/SXOS-CheatDB#17]

**Comment by rayang2004** [comment]
The cheat code of Dead Cells(EUR)  does not function

**Comment by bigbaggo** [comment]
+1 dead cell code not working

**Comment by bad1dea** [comment]
i'll buy the game and take a look.

**Comment by MentalBlank** [comment]
The cheats work for me and several other people, make sure your title and build ID's are correct and if they are try putting your switch into sleep mode and waking it back up after activating the cheats.

**Comment by MentalBlank** [comment]
Are you using version 1.0.2 of the game?

**Comment by rayang2004** [comment]
It works after I update the game to the latest verion 1.0.2 thx.
