### ISSUE TITLE
Most of the Cheat Not working for SX OS 2.2

### ISSUE THREAD

**Issue by matsui1923** [LordApple/SXOS-CheatDB#18]
DB Z figther not working and other games any update??

Can you please provide save game for DB Z fighter complete character? very much appreciated.. :)

**Comment by bad1dea** [comment]
If you want.. try this for DBZ..

Let me know if it works, I changed the pointer.. 6.0.1



[100,000,000 Zeni]
580F0000 05d47bd0
780F0000 00005ca8
640F0000 00000000 05f5e100
[100,000,000 Z Coins]
580F0000 05d47bd0
780F0000 00005cb0
640F0000 00000000 05f5e100

[All Story Mode Characters - Unlocked]
580F0000 05d47bd0
780F0000 000087b4
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001
780F0000 00000054
640F0000 00000000 00000001

[All Story Mode Characters - Level 100]
580F0000 05d47bd0
780F0000 000087a4
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064
780F0000 00000054
640F0000 00000000 00000064

[Goku (Super Saiyan) - Level 100]
580F0000 05d47bd0
780F0000 000087a4
640F0000 00000000 00000064

[Vegeta (Super Saiyan) - Unlocked]
580F0000 05d47bd0
780F0000 00008808
640F0000 00000000 00000001

[Vegeta (Super Saiyan) - Level 100]
580F0000 05d47bd0
780F0000 000087f8
640F0000 00000000 00000064

[Piccolo - Unlocked]
580F0000 05d47bd0
780F0000 0000885c
640F0000 00000000 00000001

[Piccolo - Level 100]
580F0000 05d47bd0
780F0000 0000884c
640F0000 00000000 00000064

[Gohan (Adult) - Unlocked]
580F0000 05d47bd0
780F0000 000088b0
640F0000 00000000 00000001

[Gohan (Adult) - Level 100]
580F0000 05d47bd0
780F0000 000088a0
640F0000 00000000 00000064

[Krillin - Unlocked]
580F0000 05d47bd0
780F0000 00008904
640F0000 00000000 00000001

[Krillin - Level 100]
580F0000 05d47bd0
780F0000 000088f4
640F0000 00000000 00000064

[Yamcha - Unlocked]
580F0000 05d47bd0
780F0000 00008958
640F0000 00000000 00000001

[Yamcha - Level 100]
580F0000 05d47bd0
780F0000 00008948
640F0000 00000000 00000064

[Tien - Unlocked]
580F0000 05d47bd0
780F0000 000089ac
640F0000 00000000 00000001


[Tien - Level 100]
580F0000 05d47bd0
780F0000 0000899c
640F0000 00000000 00000064


[Majin Buu - Unlocked]
580F0000 05d47bd0
780F0000 00008a00
640F0000 00000000 00000001


[Majin Buu - Level 100]
580F0000 05d47bd0
780F0000 000089f0
640F0000 00000000 00000064


[Goku (SSGSS) - Unlocked]
580F0000 05d47bd0
780F0000 00008a54
640F0000 00000000 00000001


[Goku (SSGSS) - Level 100]
580F0000 05d47bd0
780F0000 00008a44
640F0000 00000000 00000064


[Gotenks - Unlocked]
580F0000 05d47bd0
780F0000 00008aa8
640F0000 00000000 00000001


[Gotenks - Level 100]
580F0000 05d47bd0
780F0000 00008a98
640F0000 00000000 00000064


[Frieza - Unlocked]
580F0000 05d47bd0
780F0000 00008afc
640F0000 00000000 00000001


[Frieza - Level 100]
580F0000 05d47bd0
780F0000 00008aec
640F0000 00000000 00000064


[Cell - Unlocked]
580F0000 05d47bd0
780F0000 00008b50
640F0000 00000000 00000001


[Cell - Level 100]
580F0000 05d47bd0
780F0000 00008b40
640F0000 00000000 00000064


[Captain Ginyu - Unlocked]
580F0000 05d47bd0
780F0000 00008ba4
640F0000 00000000 00000001


[Captain Ginyu - Level 100]
580F0000 05d47bd0
780F0000 00008b94
640F0000 00000000 00000064


[Nappa - Unlocked]
580F0000 05d47bd0
780F0000 00008bf8
640F0000 00000000 00000001


[Nappa - Level 100]
580F0000 05d47bd0
780F0000 00008be8
640F0000 00000000 00000064


[Android 18 - Unlocked]
580F0000 05d47bd0
780F0000 00008c4c
640F0000 00000000 00000001


[Android 18 - Level 100]
580F0000 05d47bd0
780F0000 00008c3c
640F0000 00000000 00000064


[Android 16 - Unlocked]
580F0000 05d47bd0
780F0000 00008ca0
640F0000 00000000 00000001


[Android 16 - Level 100]
580F0000 05d47bd0
780F0000 00008c90
640F0000 00000000 00000064


[Android 21 (Good) - Unlocked]
580F0000 05d47bd0
780F0000 00008cf4
640F0000 00000000 00000001


[Android 21 (Good) - Level 100]
580F0000 05d47bd0
780F0000 00008ce4
640F0000 00000000 00000064


[Vegeta (SSGSS) - Unlocked]
580F0000 05d47bd0
780F0000 00008d48
640F0000 00000000 00000001


[Vegeta (SSGSS) - Level 100]
580F0000 05d47bd0
780F0000 00008d38
640F0000 00000000 00000064
