### ISSUE TITLE
For The Binding of isaac (Title ID: 01005b9002312000) pleas

### ISSUE THREAD

**Issue by Snipy44** [LordApple/SXOS-CheatDB#22]
Hello everyone !

I dont found cheat code for The Binding of isaac (Title ID: 01005b9002312000)

Do you have cheat code ? ^^'

Thank's ❤️

**Comment by GuyInDogSuit** [comment]
Might want to request in the GBAtemp thread where more people will see it.

https://gbatemp.net/threads/cheat-codes-sx-os-add-and-request.520293/

**Comment by Snipy44** [comment]
ok :(
