### ISSUE TITLE
Battle Chasers - Infinity Money (request)

### ISSUE THREAD

**Issue by adrianotabosa** [LordApple/SXOS-CheatDB#23]
Please, anyone can send cheat code for game "Battle Chasers"???

**Comment by adrianotabosa** [comment]
cheat code for money to "Battle Chasers", "Darkest Dungeon" and "Diablo 3"

**Comment by GuyInDogSuit** [comment]
Might want to request in the GBAtemp thread where more people will see it.

https://gbatemp.net/threads/cheat-codes-sx-os-add-and-request.520293/
