### ISSUE TITLE
Octopath Traveler: "error parsing cheats file"

### ISSUE THREAD

**Issue by GuyInDogSuit** [LordApple/SXOS-CheatDB#24]
SX OS 2.2.1 (and 2.1, and 2.2) could not use these codes because of this error.

"There was an error parsing the cheats file for this game!
Please check the format of the file and make sure it's correct."

**Comment by bb1bsc** [comment]
Had the same issue, not sure if its connected but i subsequebtly updated the game to latest patch and error went away.

**Comment by GuyInDogSuit** [comment]
I've been on the latest update, and it's still giving me the error.

**Comment by shizuta28** [comment]
hi there, i had the same issue:
"There was an error parsing the cheats file for this game!
Please check the format of the file and make sure it's correct."

any solution?
